
ENT.ShootAnimations = {
  ["normal"] = ACT_HL2MP_GESTURE_RANGE_ATTACK,
  ["ar2"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_AR2,
  ["camera"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_CAMERA,
  ["crossbow"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_CROSSBOW,
  ["duel"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_DUEL,
  ["fist"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_FIST,
  ["knife"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_KNIFE,
  ["magic"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_MAGIC,
  ["melee2"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_MELEE2,
  ["passive"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_PASSIVE,
  ["physgun"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_PHYSGUN,
  ["revolver"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_REVOLVER,
  ["rpg"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_RPG,
  ["shotgun"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_SHOTGUN,
  ["smg"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_SMG1,
  ["grenade"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_GRENADE,
  ["melee"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_MELEE,
  ["pistol"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_PISTOL,
  ["slam"] = ACT_HL2MP_GESTURE_RANGE_ATTACK_SLAM
}

ENT.ReloadAnimations = {
  ["normal"] = ACT_HL2MP_GESTURE_RELOAD,
  ["ar2"] = ACT_HL2MP_GESTURE_RELOAD_AR2,
  ["camera"] = ACT_HL2MP_GESTURE_RELOAD_CAMERA,
  ["crossbow"] = ACT_HL2MP_GESTURE_RELOAD_CROSSBOW,
  ["duel"] = ACT_HL2MP_GESTURE_RELOAD_DUEL,
  ["fist"] = ACT_HL2MP_GESTURE_RELOAD_FIST,
  ["knife"] = ACT_HL2MP_GESTURE_RELOAD_KNIFE,
  ["magic"] = ACT_HL2MP_GESTURE_RELOAD_MAGIC,
  ["melee2"] = ACT_HL2MP_GESTURE_RELOAD_MELEE2,
  ["passive"] = ACT_HL2MP_GESTURE_RELOAD_PASSIVE,
  ["physgun"] = ACT_HL2MP_GESTURE_RELOAD_PHYSGUN,
  ["revolver"] = ACT_HL2MP_GESTURE_RELOAD_REVOLVER,
  ["rpg"] = ACT_HL2MP_GESTURE_RELOAD_RPG,
  ["shotgun"] = ACT_HL2MP_GESTURE_RELOAD_SHOTGUN,
  ["smg"] = ACT_HL2MP_GESTURE_RELOAD_SMG1,
  ["grenade"] = ACT_HL2MP_GESTURE_RELOAD_GRENADE,
  ["melee"] = ACT_HL2MP_GESTURE_RELOAD_MELEE,
  ["pistol"] = ACT_HL2MP_GESTURE_RELOAD_PISTOL,
  ["slam"] = ACT_HL2MP_GESTURE_RELOAD_SLAM
}

if SERVER then

  function ENT:GetShootAnimation()
    if not self:HasWeapon() then return end
    return self.ShootAnimations[self:GetWeapon():GetHoldType()]
  end

  function ENT:GetReloadAnimation()
    if not self:HasWeapon() then return end
    return self.ReloadAnimations[self:GetWeapon():GetHoldType()]
  end

end
