DRGBASE_STATE_ERROR = -1
DRGBASE_STATE_NONE = 0
DRGBASE_STATE_CUSTOM = 1
DRGBASE_STATE_POSSESSED = 2
DRGBASE_STATE_AI_WANDER = 3
DRGBASE_STATE_AI_PATROL = 3
DRGBASE_STATE_AI_SUSPICIOUS = 4
DRGBASE_STATE_AI_REGROUP = 5
DRGBASE_STATE_AI_FOLLOW = 6
DRGBASE_STATE_AI_STANDBY = 7
DRGBASE_STATE_AI_AVOID = 8
DRGBASE_STATE_AI_FIGHT = 9

DRGBASE_POSSESS_ERROR = -1
DRGBASE_POSSESS_OK = 0
DRGBASE_POSSESS_INVALID = 1
DRGBASE_POSSESS_NOT_PLAYER = 2
DRGBASE_POSSESS_NOT_ALIVE = 3
DRGBASE_POSSESS_ALREADY = 4
DRGBASE_POSSESS_NOT_EMPTY = 5
DRGBASE_POSSESS_NOT_ALLOWED = 6
DRGBASE_POSSESS_DISABLED = 7
DRGBASE_POSSESS_NOVIEWS = 8

DRGBASE_DISPOSSESS_ERROR = -1
DRGBASE_DISPOSSESS_OK = 0
DRGBASE_DISPOSSESS_EMPTY = 1
DRGBASE_DISPOSSESS_NOT_ALLOWED = 2

NODE_TYPE_GROUND = 2
NODE_TYPE_AIR = 3
NODE_TYPE_CLIMB = 4
NODE_TYPE_WATER = 5

DRGBASE_VARS_INVALID = -1
DRGBASE_VARS_ANGLE = 0
DRGBASE_VARS_BOOL = 1
DRGBASE_VARS_ENTITY = 2
DRGBASE_VARS_NUMBER = 3
DRGBASE_VARS_STRING = 4
DRGBASE_VARS_VECTOR = 5
DRGBASE_VARS_TABLE = 6

DRGBASE_FACTION_REBELS = "HL2_REBELS"
DRGBASE_FACTION_COMBINE = "HL2_COMBINE"
DRGBASE_FACTION_ANIMALS = "HL2_ANIMALS"
DRGBASE_FACTION_ZOMBIES = "HL2_ZOMBIES"
DRGBASE_FACTION_ANTLIONS = "HL2_ANTLIONS"
DRGBASE_FACTION_GMAN = "HL2_GMAN"
DRGBASE_FACTION_BARNACLES = "HL2_BARNACLES"
DRGBASE_FACTION_SANIC = "SHITTY_SANIC_CLONES"
DRGBASE_FACTION_XEN_ARMY = "HL_XEN_ARMY"
DRGBASE_FACTION_XEN_WILDLIFE = "HL_XEN_WILDLIFE"
DRGBASE_FACTION_HECU = "HL_HECU"

DRGBASE_ANIMTYPE_NONE = 0
DRGBASE_ANIMTYPE_FORWARD = 1
DRGBASE_ANIMTYPE_DIRECTION = 2
DRGBASE_ANIMTYPE_BODYMOVEXY = 3
DRGBASE_ANIMTYPE_MATCH = 4
DRGBASE_ANIMTYPE_BOTH = 5

DRGBASE_AMMO_INFINITE = -1

DRGBASE_FLIGHT_HOVER = 0
