DRGBASE_STATE_ERROR = -1
DRGBASE_STATE_NONE = 0
DRGBASE_STATE_CUSTOM = 1
DRGBASE_STATE_POSSESSED = 2
DRGBASE_STATE_AI_WANDER = 3
DRGBASE_STATE_AI_STANDBY = 4
DRGBASE_STATE_AI_AVOID = 5
DRGBASE_STATE_AI_SEARCH = 6
DRGBASE_STATE_AI_PURSUE = 7
DRGBASE_STATE_AI_FIGHT = 7

NODE_TYPE_GROUND = 2
NODE_TYPE_AIR = 3
NODE_TYPE_CLIMB = 4
NODE_TYPE_WATER = 5

DRGBASE_VARS_INVALID = -1
DRGBASE_VARS_ANGLE = 0
DRGBASE_VARS_BOOL = 1
DRGBASE_VARS_ENTITY = 2
DRGBASE_VARS_NUMBER = 3
DRGBASE_VARS_STRING = 4
DRGBASE_VARS_VECTOR = 5
DRGBASE_VARS_TABLE = 6

DRGBASE_FACTION_REBELS = "HL2_REBELS"
DRGBASE_FACTION_COMBINE = "HL2_COMBINE"
DRGBASE_FACTION_ANIMALS = "HL2_ANIMALS"
DRGBASE_FACTION_ZOMBIES = "HL2_ZOMBIES"
DRGBASE_FACTION_ANTLIONS = "HL2_ANTLIONS"
DRGBASE_FACTION_GMAN = "HL2_GMAN"
DRGBASE_FACTION_BARNACLES = "HL2_BARNACLES"
DRGBASE_FACTION_SANIC = "SHITTY_SANIC_CLONES"
DRGBASE_FACTION_XEN_ARMY = "HL_XEN_ARMY"
DRGBASE_FACTION_XEN_WILDLIFE = "HL_XEN_WILDLIFE"
DRGBASE_FACTION_HECU = "HL_HECU"

DRGBASE_AMMO_INFINITE = -1

DRGBASE_FLIGHT_HOVER = 0
