DRGBASE_NEXTBOT_STATE_NONE = 0
DRGBASE_NEXTBOT_STATE_TARGET = 1
DRGBASE_NEXTBOT_STATE_DESTINATION = 2
DRGBASE_NEXTBOT_STATE_BEHAVIOUR = 3
DRGBASE_NEXTBOT_STATE_POSSESSED = 4

DRGBASE_NEXTBOT_POSSESS_OK = 0
DRGBASE_NEXTBOT_POSSESS_NOT_ALLOWED = 1
DRGBASE_NEXTBOT_POSSESS_NOT_EMPTY = 2
DRGBASE_NEXTBOT_DISPOSSESS_OK = 3
DRGBASE_NEXTBOT_DISPOSSESS_NOT_ALLOWED = 4
DRGBASE_NEXTBOT_DISPOSSESS_EMPTY = 5
DRGBASE_NEXTBOT_POSSESS_HOOK_DISABLED = 6
DRGBASE_NEXTBOT_DISPOSSESS_HOOK_DISABLED = 7
DRGBASE_NEXTBOT_POSSESS_ALREADY = 8
DRGBASE_NEXTBOT_POSSESS_INVALID = 9
DRGBASE_NEXTBOT_POSSESS_NOT_PLAYER = 10
DRGBASE_NEXTBOT_POSSESS_NOT_ALIVE = 11

DRGBASE_NEXTBOT_COMBINE_BALL_IGNORE = 0
DRGBASE_NEXTBOT_COMBINE_BALL_DISSOLVE = 1
DRGBASE_NEXTBOT_COMBINE_BALL_BOUNCE = 2
DRGBASE_NEXTBOT_COMBINE_BALL_EXPLODE = 3

NODE_TYPE_GROUND = 2
NODE_TYPE_AIR = 3
NODE_TYPE_CLIMB = 4
NODE_TYPE_WATER = 5

DRGBASE_VARS_INVALID = 1
DRGBASE_VARS_ANGLE = 0
DRGBASE_VARS_BOOL = 1
DRGBASE_VARS_ENTITY = 2
DRGBASE_VARS_NUMBER = 3
DRGBASE_VARS_STRING = 4
DRGBASE_VARS_VECTOR = 5
DRGBASE_VARS_TABLE = 6

DRGBASE_RELATIONSHIP_IGNORE = 0
DRGBASE_RELATIONSHIP_HATE = 1
DRGBASE_RELATIONSHIP_HATEFEAR = 2
DRGBASE_RELATIONSHIP_FEARHATE = 3
DRGBASE_RELATIONSHIP_LIKE = 4
DRGBASE_RELATIONSHIP_FOLLOW = 5
DRGBASE_RELATIONSHIP_PROTECT = 6
