NODE_TYPE_GROUND = 2
NODE_TYPE_AIR = 3
NODE_TYPE_CLIMB = 4
NODE_TYPE_WATER = 5

FACTION_REBELS = "FACTION_HL2_REBELS"
FACTION_COMBINE = "FACTION_HL2_COMBINE"
FACTION_ANIMALS = "FACTION_HL2_ANIMALS"
FACTION_ZOMBIES = "FACTION_HL2_ZOMBIES"
FACTION_ANTLIONS = "FACTION_HL2_ANTLIONS"
FACTION_GMAN = "FACTION_HL2_GMAN"
FACTION_BARNACLES = "FACTION_HL2_BARNACLES"
FACTION_SANIC = "FACTION_SHITTY_SANIC_CLONES"
FACTION_XEN_ARMY = "FACTION_HL_XEN_ARMY"
FACTION_XEN_WILDLIFE = "FACTION_HL_XEN_WILDLIFE"
FACTION_HECU = "FACTION_HL_HECU"

POSSESSION_MOVE_CUSTOM = 0
POSSESSION_MOVE_8DIR = 1
POSSESSION_MOVE_NSEW = 1
POSSESSION_MOVE_COMPASS = 1
POSSESSION_MOVE_1DIR = 2
POSSESSION_MOVE_FORWARD = 2
POSSESSION_MOVE_4DIR = 3

AI_BEHAV_CUSTOM = 0
AI_BEHAV_BASE = 1
AI_BEHAV_HUMAN = 2

PATROL_POS = 0
PATROL_SEARCH = 100
PATROL_SOUND = 200

IN_ATTACK3 = 33554432

if CLIENT then

	D_ER = 0
	D_HT = 1
	D_FR = 2
	D_LI = 3
	D_NU = 4

end
