-- Global

IN_ATTACK3 = 33554432

if CLIENT then

  D_ER = 0
  D_HT = 1
  D_FR = 2
  D_LI = 3
  D_NU = 4

end

-- DrGBase

AI_BEHAV_CUSTOM = 0
AI_BEHAV_BASE = 1
AI_BEHAV_HUMAN = 2

POSSESSION_MOVE_CUSTOM = 0
POSSESSION_MOVE_8DIR = 1
POSSESSION_MOVE_NSEW = 1 -- use 8DIR
POSSESSION_MOVE_COMPASS = 1 -- use 8DIR
POSSESSION_MOVE_1DIR = 2
POSSESSION_MOVE_FORWARD = 2 -- use 1DIR
POSSESSION_MOVE_4DIR = 3

SIGHT_TEST_LOS = 1
SIGHT_TEST_RANGE = 2
SIGHT_TEST_ANGLE = 4
SIGHT_TEST_LUMINOSITY = 8
SIGHT_TEST_PASSED_ALL =
  SIGHT_TEST_LOS +
  SIGHT_TEST_RANGE +
  SIGHT_TEST_ANGLE +
  SIGHT_TEST_LUMINOSITY