
NODE_TYPE_GROUND = 2
NODE_TYPE_AIR = 3
NODE_TYPE_CLIMB = 4
NODE_TYPE_WATER = 5

DRGBASE_FACTION_REBELS = "FACTION_HL2_REBELS"
DRGBASE_FACTION_COMBINE = "FACTION_HL2_COMBINE"
DRGBASE_FACTION_ANIMALS = "FACTION_HL2_ANIMALS"
DRGBASE_FACTION_ZOMBIES = "FACTION_HL2_ZOMBIES"
DRGBASE_FACTION_ANTLIONS = "FACTION_HL2_ANTLIONS"
DRGBASE_FACTION_GMAN = "FACTION_HL2_GMAN"
DRGBASE_FACTION_BARNACLES = "FACTION_HL2_BARNACLES"
DRGBASE_FACTION_SANIC = "FACTION_SHITTY_SANIC_CLONES"
DRGBASE_FACTION_XEN_ARMY = "FACTION_HL_XEN_ARMY"
DRGBASE_FACTION_XEN_WILDLIFE = "FACTION_HL_XEN_WILDLIFE"
DRGBASE_FACTION_HECU = "FACTION_HL_HECU"

if SERVER then



else

  D_ER = 0
  D_HT = 1
  D_FR = 2
  D_LI = 3
  D_NU = 4

end
