SWEP.PrintName = "Possession"
SWEP.Spawnable = false
SWEP.AdminOnly = true
SWEP.AutoSwitchTo = false
SWEP.DrawAmmo = false
SWEP.DisableDuplicator = true
SWEP.Primary.Ammo = ""
SWEP.Secondary.Ammo = ""
function SWEP:PrimaryAttack() end
function SWEP:SecondaryAttack() end
function SWEP:Reload() end
